<?php

/*----- Include Files -----*/
include_once('../includes/configs/init.php');

/*----- Procedure Call and Coding Part Start-----*/
$templates_obj = new templates();

function generate_label_xml($tid)
{
    global $templates_obj;

    $args["tablename"]="tbl_template_captions";
    $args["whereCon"]='p1te_id ='.$tid.' and p1tc_type =1 order by  p1tc_id asc';
    $homeallcaptions = $templates_obj->get_all($args);//Get all updated captions details.
    
    $args1["tablename"]="tbl_template_captions";
    $args1["whereCon"]='p1te_id ='.$tid.' and p1tc_type =2 order by  p1tc_id asc';
    $moballcaptions = $templates_obj->get_all($args1);//Get all updated captions details.
        
    //Coding for xml file creation for updated labels
    $dom = new DOMDocument("1.0");
    $dom->encoding = "utf-8";
    $gendetails = $dom->createComment('Generated by PaymentOne.com');// Create a comment
    $dom->appendChild($gendetails);// Put this comment at the Root of the XML doc
    $tempdetails = $dom->createComment('label details for paymentone template');
    $dom->appendChild($tempdetails);// Put this comment at the Root of the XML doc
    $root1 = $dom->createElement("PaymentOne");
    $dom->appendChild($root1);
    $dom->formatOutput=true;
    $root = $dom->createElement("Home");
    $dom->appendChild($root);
    $dom->formatOutput=true;
    $root1->appendChild( $root );
    foreach( $homeallcaptions as $hlabels )
    {           
        $name = $dom->createElement( "homelabel" );        
        $attrb = $dom->createAttribute("for");// create attribute node
        $name->appendChild($attrb);            
        $value = $dom->createTextNode($hlabels['p1tc_title']);// create attribute value node
        $attrb->appendChild($value);        
        $name->appendChild(
            $dom->createTextNode( $hlabels['p1tc_value'] )
        );  
        $root->appendChild( $name );
    }
    $root = $dom->createElement("Mobile");
    $dom->appendChild($root);
    $dom->formatOutput=true;
    $root1->appendChild( $root );
    foreach( $moballcaptions as $mlabels )
    {
        $name = $dom->createElement( "mobilelabel" );        
        $attrb = $dom->createAttribute("for");// create attribute node
        $name->appendChild($attrb);            
        $value = $dom->createTextNode($mlabels['p1tc_title']);// create attribute value node
        $attrb->appendChild($value);        
        $name->appendChild(
            $dom->createTextNode( $mlabels['p1tc_value'] )
        );  
        $root->appendChild( $name );
    }    
    $filename = (FULL_PATH."/data/xml/templates/template_".$tid);
    if (file_exists($filename))
    { 
        $dom->save($filename."/labels.xml");// save tree to file
        chmod($filename."/labels.xml", 0777);
    }
    else
    {
        mkdir($filename, 0777);
        chmod($filename,  0777);
        $dom->save($filename."/labels.xml");// save tree to file
        chmod($filename."/labels.xml", 0777);
    }
}



$args["tablename"]="tbl_template_captions";
$args["whereCon"]="p1tc_title ='Sorry, Your transaction has been cancelled due to the wrong authentications.' and p1tc_type=2";
$debug = array('file'=>'templatefunctions.class.php', 'line'=>'getall_homelables');
$tmpslistcnt = $templates_obj->get_all($args,$debug);/*getall_homelables*/

$title="Sorry, there was a problem with your purchase.";
$value="Sorry, there was a problem with your purchase.";


foreach($tmpslistcnt as $caps){
$args["tablename"] = "tbl_template_captions";
$args["fieldname"] = "p1tc_value = '".addslashes($value)."' , p1tc_title = '".addslashes($title)."' ";
$args["whereCon"] = 'p1te_id ='.$caps['p1te_id']." and p1tc_id='".$caps['p1tc_id']."'";
$debug = array('file'=>'templatefunctions.class.php', 'line'=>'updatestyle_restorelabel');
$template_update =$templates_obj->update_styles($args,$debug);/*updatestyle_restorelabel*/
generate_label_xml($caps['p1te_id']);
     $count++;
    if($count == 100)
    {
        echo "<br/>sleeping<br/>";
        sleep(5);
        $count = 1;
    }

}


// second label

$args["tablename"]="tbl_template_captions";
$args["whereCon"]="p1tc_title ='Mobile number validated successfully.' and p1tc_type=2";
$debug = array('file'=>'templatefunctions.class.php', 'line'=>'getall_homelables');
$tmpslistcnt = $templates_obj->get_all($args,$debug);/*getall_homelables*/

$title="Pay with your Mobile Phone";
$value="Pay with your Mobile Phone";


foreach($tmpslistcnt as $caps){
$args["tablename"] = "tbl_template_captions";
$args["fieldname"] = "p1tc_value = '".addslashes($value)."' , p1tc_title = '".addslashes($title)."' ";
$args["whereCon"] = 'p1te_id ='.$caps['p1te_id']." and p1tc_id='".$caps['p1tc_id']."'";
$debug = array('file'=>'templatefunctions.class.php', 'line'=>'updatestyle_restorelabel');
$template_update =$templates_obj->update_styles($args,$debug);/*updatestyle_restorelabel*/
generate_label_xml($caps['p1te_id']);
     $count++;
    if($count == 100)
    {
        sleep(5);
        $count = 1;
    }

}


echo "Update Completed";

?>