<?php
//-------------------------------------------------------------------------------------------------------------------
// File name   : autosave.php
// Description : File to handle - save UI Template form values automatically.
//
// © 2010-2011 PaymentOne Corportation. All rights reserved.
//
// Created date : 19-03-2010
// Modified date: 28-11-2011
// ------------------------------------------------------------------------------------------------------------------

/*----- Include Files -----*/
include_once('../includes/configs/init.php');

/*----- Instantiate the class -----*/
$templates_obj = new templates();
$debug_obj = new Debug();
$template_func_obj = new TemplateFunctions();

$type = $_POST['types'];
$tid = $_POST['tid'];
$nextid =$_POST['nextid'];
$orgvalue =addslashes($_POST['orgvalue']);
$coun_lang_id = $_SESSION['temp_coun_lang_id'];
$country_code = $_SESSION['temp_country_code'];
$language_code = $_SESSION['temp_language_code'];

//To update the selected ui templates with new label - starts
if($type == 'label')
{
    $caption = addslashes($_POST['caps']);
    $lid = $_POST['lid'];
    if($caption != $orgvalue) { //if value is changed update it to db
        $update_caption["tablename"] = "tbl_template_captions";
        $update_caption["fieldname"] = "p1tc_value = '".addslashes($caption)."'";
        $update_caption["whereCon"] = "p1te_id =".$tid." and p1tc_id=".$lid;
        $debug = array('file'=>'autosave.php', 'line'=>'updatelabels');
        $template_update =$templates_obj->update_styles($update_caption, $debug);/*updatelabels*/
        echo "updated";
    }

    //Get all home labels
    $get_caption1["tablename"]="tbl_template_captions";
    $get_caption1["whereCon"]='p1te_id ='.$tid.' and p1tc_type = 1 and p1colg_id = '.$coun_lang_id.' order by  p1tc_id asc';
    $debug = array('file'=>'autosave.php', 'line'=>'gethomelabels');
    $homeallcaptions = $templates_obj->get_all($get_caption1, $debug);/*gethomelabels*/

    //Get all mobile labels
    $get_caption2["tablename"]="tbl_template_captions";
    $get_caption2["whereCon"]='p1te_id ='.$tid.' and p1tc_type = 2 and p1colg_id = '.$coun_lang_id.' order by  p1tc_id asc';
    $debug = array('file'=>'autosave.php', 'line'=>'getmobilelabels');
    $moballcaptions = $templates_obj->get_all($get_caption2, $debug);/*getmobilelabels*/

    //Get all anyphone labels
    $get_caption3["tablename"]="tbl_template_captions";
    $get_caption3["whereCon"]='p1te_id ='.$tid.' and p1tc_type = 3 and p1colg_id = '.$coun_lang_id.' order by  p1tc_id asc';
    $debug = array('file'=>'autosave.php', 'line'=>'getanyphonelabels');
    $anyphonecaptions = $templates_obj->get_all($get_caption3, $debug);/*getanyphonelabels*/

    //Coding for xml file creation
    $dom = new DOMDocument("1.0");
    $dom->encoding = "utf-8";
    $gendetails = $dom->createComment('Generated by PaymentOne.com');// Create a comment
    $dom->appendChild($gendetails);
    $tempdetails = $dom->createComment('label details for paymentone template');//comments
    $dom->appendChild($tempdetails);

    $root1 = $dom->createElement("PaymentOne");
    $attrb = $dom->createAttribute("country_code");// create country node
    $root1->appendChild($attrb);
    $value = $dom->createTextNode($country_code);
    $attrb->appendChild($value);
    $attrb = $dom->createAttribute("language_code");// create language node
    $root1->appendChild($attrb);
    $value = $dom->createTextNode($language_code);
    $attrb->appendChild($value);
    $dom->appendChild($root1);
    $dom->formatOutput=true;

    $root = $dom->createElement("Home");//home array
    $dom->appendChild($root);
    $dom->formatOutput=true;
    $root1->appendChild( $root );
    foreach( $homeallcaptions as $hlabels ) {
        $name = $dom->createElement( "homelabel" );
        $attrb = $dom->createAttribute("for");// create attribute node
        $name->appendChild($attrb);
        $value = $dom->createTextNode($hlabels['p1tc_title']);// create attribute value node
        $attrb->appendChild($value);
        $name->appendChild(
            $dom->createTextNode( $hlabels['p1tc_value'] )
        );
        $root->appendChild( $name );
    }

    $root = $dom->createElement("Mobile");//mobile array
    $dom->appendChild($root);
    $dom->formatOutput=true;
    $root1->appendChild( $root );
    foreach( $moballcaptions as $mlabels ) {
        $name = $dom->createElement( "mobilelabel" );
        $attrb = $dom->createAttribute("for");// create attribute node
        $name->appendChild($attrb);
        $value = $dom->createTextNode($mlabels['p1tc_title']);// create attribute value node
        $attrb->appendChild($value);
        $name->appendChild(
            $dom->createTextNode( $mlabels['p1tc_value'] )
        );
        $root->appendChild( $name );
    }

    $root = $dom->createElement("Anyphone");//anyphone array
    $dom->appendChild($root);
    $dom->formatOutput=true;
    $root1->appendChild( $root );
    foreach( $anyphonecaptions as $anylabels ) {
        $name = $dom->createElement( "anyphonelabel" );
        $attrb = $dom->createAttribute("for");// create attribute node
        $name->appendChild($attrb);
        $value = $dom->createTextNode($anylabels['p1tc_title']);// create attribute value node
        $attrb->appendChild($value);
        $name->appendChild(
            $dom->createTextNode( $anylabels['p1tc_value'] )
        );
        $root->appendChild( $name );
    }

    $filename = "../data/xml/templates/template_".$tid."/";
    $country_path = $filename.$country_code."/";
    $template_path = $country_path.'labels_'.$language_code.'.xml';
    if(file_exists($country_path))
    {
        //chmod($country_path, 0777);
         if(file_exists($template_path))
        {
            //chmod($template_path, 0777);
            $dom->save($template_path);// save tree to file
            //chmod($template_path, 0777);
        }
        else
        {
            fopen($template_path, "w");
            chmod($template_path, 0777);
            $dom->save($template_path);// save tree to file
            chmod($template_path, 0777);
        }
    }
    else
    {
        mkdir($country_path, 0777);
        chmod($country_path, 0777);
        fopen($template_path, "w");
        chmod($template_path, 0777);
        $dom->save($template_path);// save tree to file
        chmod($template_path, 0777);
    }
}
//To update the selected ui templates with new label - ends
//To update the selected ui templates with new css - starts
else
{
    $cid = $_POST['cid'];
    $debug = array('file'=>'autosave.php', 'line'=>'checkstylechanges');
    $fetch_changes = $template_func_obj->check_style_changes($cid, $debug);/*checkstylechanges*/
    foreach( $_POST as $key => $value)
    {
        if($key == 'tid' || $key == 'cid' || $key == 'type')
        {
            //No Action.
        }
        else
        {
            if($value != '')
            {
                $args["tablename"] = "tbl_template_attribs";
                $args["fieldname"] = "p1ta_value = '".$value."'";
                if($key == 'FontSize')//to change the FontSize of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Font-Size'";
                }
                elseif($key == 'FontFamily')//to change the FontFamily of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Font-Family'";
                }
                elseif($key == 'TextDecoration')//to change the TextDecoration of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Text-Decoration'";
                }
                elseif($key == 'TextAlign')//to change the TextAlign of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Text-Align'";
                }
                elseif($key == 'FontWeight')//to change the FontWeight of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Font-Weight'";
                }
                elseif($key == 'FontStyle')//to change the FontStyle of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Font-Style'";
                }
                elseif($key == 'BackgroundColor')//to change the BackgroundColor of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Background-Color'";
                }
                elseif($key == 'Background')//to change the Background of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Background'";
                }
                elseif($key == 'BorderColor')//to change the BorderColor of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Border-Color'";
                }
                elseif($key == 'BorderBottomColor')//to change the BorderBottomColor of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Border-Bottom-Color'";
                }
                elseif($key == 'BorderLeftColor')//to change the BorderLeftColor of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Border-Left-Color'";
                }
                elseif($key == 'BorderTopColor')//to change the BorderTopColor of the selected ui template
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='Border-Top-Color'";
                }
                else
                {
                    $args["whereCon"] = "p1tv_id =".$cid." and p1ta_title='".$key."'";
                }
                //update query for selected template
                $debug = array('file'=>'autosave.php', 'line'=>'applystyles');
                $template_update =$templates_obj->update_styles($args, $debug);/*applystyles*/
            }
        }
    }

    //Get all components - styles
    $get_components["tablename"]="tbl_template_vars";
    $get_components["whereCon"]="p1te_id =".$tid;
    $debug = array('file'=>'autosave.php', 'line'=>'fetchstyles');
    $allcomponents = $templates_obj->get_all($get_components, $debug);/*fetchstyles*/
    foreach( $allcomponents as $key => $value) {
        $get_components = '';
        $get_components["tablename"]="tbl_template_attribs";
        $get_components["whereCon"]= "p1tv_id = ".$value['p1tv_id'];
        $debug = array('file'=>'autosave.php', 'line'=>'fetchselectstyles');
        $listallattributes = $templates_obj->get_all($get_components, $debug);/*fetchselectstyles*/
        $valu .= $value['p1tv_value'];
        $valu .= " { ";
        foreach( $listallattributes as $key => $style) {
            $valu .= $style['p1ta_title'];
            $valu .= ": ";
            $valu .= $style['p1ta_value'];
            $valu .= "; ";
        }
        $valu .= " }\n";
    }

    $filename = ("../data/styles/templates/template_".$_POST[tid]);
    if(file_exists($filename)) {
        $fh = fopen('../data/styles/templates/template_'.$_POST[tid].'/merchant.css', 'w');
        fwrite($fh, $valu);
    }
    else {
        mkdir("../data/styles/$_POST[tid]", 0777);
        $fh = fopen('../data/styles/templates/template_'.$_POST[tid].'/merchant.css', 'w');
        fwrite($fh, $valu);
    }
    print_r($fetch_changes);
}
//To update the selected ui templates with new css - ends

?>